steps:
  - label: ":buildkite: example step"
    command: echo 1st step 

  - label: ":buildkite: pwd"
    command: pwd

  - label: ":buildkite: echo user"
    command: echo $USER
  
  - label: ":docker: build image"
    command: docker build -t buildkite-example .
    key: build

  - label: ":docker: run image"
    command: docker run buildkite-example
    key: run
    depends_on: build
