steps:
  - label: ":buildkite: example step"
    command: echo 1st step 

  - label: ":buildkite: pwd"
    command: pwd

  - label: ":buildkite: echo user"
    command: echo $USER
  
  - label: ":docker: build image"
    command: docker build -t buildkite-example .
